### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Dracula1998** [Sxyyyyyy/SWP-of-searchable-encryption#1]
您好，在步骤2.2.2 make的过程中出现了编译错误，但是我在abseil中确实找到了对应的函数，请问这可能是哪方面的问题呢？
![issue](https://github.com/Suxyuuu/SWP-of-searchable-encryption/assets/28029289/3bf371b3-68f6-4bc8-82b3-921b1a47f4e8)

**Comment by Suxyuuu** [comment]
@Dracula1998 看报错是该函数调用错误，但正常而言库函数不会有该问题的，那大概率是版本问题了。建议重新确认版本。
