### ISSUE TITLE
关于搜索

### ISSUE THREAD

**Issue by qingy1997** [Sxyyyyyy/SWP-of-searchable-encryption#2]
您好，我在swp中的help说明中发现想要查询某个value值时，需要调用search [value]，并且value是明文。而我看您有提前在rocksdb中存储了一些数据，那请问如果我想查看一下search的演示过程，这个value有哪些可以尝试呀，也就是说是否需要您告知目前在rocksdb存储信息的明文形式呀?

**Comment by qingy1997** [comment]
> 您好，我在swp中的help说明中发现想要查询某个value值时，需要调用search [value]，并且value是明文。而我看您有提前在rocksdb中存储了一些数据，那请问如果我想查看一下search的演示过程，这个value有哪些可以尝试呀，也就是说是否需要您告知目前在rocksdb存储信息的明文形式呀？

**Comment by qingy1997** [comment]
上述问题已解决，麻烦了！另外如果想测试这个方案在较大数据量下的性能，每次add是只能向某个列族中插入一个键值对吗，这样感觉比较繁琐，请问是否还有其他办法可以进行批量操作吗？另外每个列族中可存储的键值对数量是否有限制呢？

**Comment by Suxyuuu** [comment]
@qingy1997 

关于批量add可以参考random批量生成的时候的实现，应该是类似的（rocksdb支持向数据库进行批量增加）。至于性能，可以参考SWP方案本身的限制与rocksdb本身的限制。

**Comment by qingy1997** [comment]
> @qingy1997
> 
> 关于批量add可以参考random批量生成的时候的实现，应该是类似的（rocksdb支持向数据库进行批量增加）。至于性能，可以参考SWP方案本身的限制与rocksdb本身的限制。

您好，我批量插入了50个列族，其中每个列族涉及10个键值对（如果我理解没错的话，这个列族是否对应了文件数量，而键值对则是该文件中划分的单词数），但此时查询失败了，是否说明本方案不支持较大数据（文件数），另外server也会突然断联
<img width="373" alt="1686405081879" src="https://github.com/Suxyuuu/SWP-of-searchable-encryption/assets/136093549/36999e83-d49d-44f2-86f8-ac6cd448a239">

<img width="369" alt="1686409694458" src="https://github.com/Suxyuuu/SWP-of-searchable-encryption/assets/136093549/767d4749-f4e8-4d5a-88f0-bf032acdfdc0">

**Comment by Suxyuuu** [comment]
> 是否说明本方案不支持较大数据（文件数），另外server也会突然断联

按照正常理解来说，search的过程最差不过是逐个遍历，费点时间罢了。感觉目前这情况应该是代码某个地方的写法不是兼容性的，造成了bug。

**Comment by qingy1997** [comment]
> 

您好，除搜索外，我在初始化数据库时，rangen [n]当n取较大值时，服务器会断开，显示段错误（核心已转储），从而使得client与服务器连接失败，导致数据写入失败，请问其原因可能是因为什么呀？
<img width="754" alt="1686558555871" src="https://github.com/Suxyuuu/SWP-of-searchable-encryption/assets/136093549/72088ad7-b3ab-4e38-b7b5-809f1e728302">

**Comment by Suxyuuu** [comment]
> 服务器会断开，显示段错误（核心已转储）

虚拟机内存多大？是不是爆内存了？代码上来说不应该出现这种情况的。
